print("We are the so-called \"Vikings\" from the north.")
print('It\'s alright.')
print("This will insert one \\ (backslash).")
print("Hello\nWorld!")
print("Hello\rWorld!")
print("Hello\tWorld!")
print("Hello\bWorld!")
